name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Correct version for pages artifact
        with:
          path: '.'  # This tells the action to deploy the files from the root directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
